name: foct_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.11.0
  webview_windows: ^0.4.0
  google_maps_flutter: ^2.17.0
  shared_preferences: ^2.5.5
  http: ^1.6.0
  url_launcher: ^6.3.2
  share_plus: ^13.2.0
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/footer.png
    - assets/robot.png
    - assets/logo1.png
    - assets/footer.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"